"""Reproducibly import V2 rows without changing the original Markdown."""
import html
import json
import re
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POSITIONS = {"Verb": "verb", "Adjective/Adverb": "adjective-adverb", "Noun": "noun", "Phrase": "phrase"}
# Explicit per-entry semantic annotations, not spaCy predictions. New entries are
# never silently classified as general; a changed source must be reviewed again.
ANNOTATIONS = json.loads((ROOT / "data/domain_annotations.json").read_text(encoding="utf-8"))


def domains_for(entry_id, term, meaning, pos):
    annotation = ANNOTATIONS["entries"].get(entry_id)
    if annotation and (annotation["term"], annotation["meaning"], annotation["pos"]) == (term, meaning, pos):
        return list(annotation["domains"])
    return []


def plain(value):
    return html.unescape(re.sub(r"<[^>]+>", "", value)).strip().strip("*`").strip()


def parse_markdown(text):
    entries = []
    position = None
    for line_number, line in enumerate(text.splitlines(), 1):
        if line.startswith("## "):
            position = POSITIONS.get(line[3:].split(" <")[0].strip())
        if not position or not line.startswith("|"):
            continue
        cells = re.split(r"(?<!\\)\|", line.strip().strip("|"))
        for offset in range(0, len(cells) - 3, 4):
            number, term, meaning, details = [x.strip() for x in cells[offset:offset + 4]]
            if not number.isdigit() or not term or (term == "word" and meaning == "中文"):
                continue
            match = re.search(r"`([^`]+)`", details)
            example = plain(match.group(1)) if match else ""
            source = plain(details.split("`", 2)[-1]) if match else ""
            if example.lower() in {"sentence.", "sentence"}:
                example, source = "", ""
            entry_id = str(uuid.uuid5(uuid.NAMESPACE_URL, f"vocab-v2:{line_number}:{offset}"))
            entries.append({
                "id": entry_id,
                "term": plain(term), "meaning": plain(meaning), "pos": position,
                "domains": domains_for(entry_id, plain(term), plain(meaning), position), "tags": [],
                "example": example, "source": source, "source_url": "",
                "owner_id": None, "author_name": "Jing Zhang · 原始词表",
                "provenance": f"glossary_v2.md:L{line_number}", "revision": 1,
            })
    return entries


def main():
    entries = parse_markdown((ROOT / "docs/glossary_v2.md").read_text(encoding="utf-8"))
    missing = [entry["term"] for entry in entries if not entry["domains"]]
    if missing:
        raise ValueError(f"Review data/domain_annotations.json for new or changed entries before rebuilding: {missing}")
    target = ROOT / "docs/data/vocabulary.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    payload = json.dumps(entries, ensure_ascii=False)
    sql = "-- Generated by scripts/migrate_glossary.py. Re-runs never overwrite community edits.\n"
    sql += "insert into public.entries (id, term, meaning, pos, domains, tags, example, source, source_url, author_name, provenance)\n"
    sql += "select id, term, meaning, pos, domains, tags, example, source, source_url, author_name, provenance\n"
    sql += "from jsonb_to_recordset($vocab$" + payload + "$vocab$::jsonb) as x(\n"
    sql += "id uuid, term text, meaning text, pos text, domains text[], tags text[], example text, source text, source_url text, author_name text, provenance text)\non conflict (id) do nothing;\n"
    (ROOT / "supabase/seed.sql").write_text(sql, encoding="utf-8")
    print(f"Imported {len(entries)} entries, {sum(bool(e['example']) for e in entries)} with examples.")


if __name__ == "__main__":
    main()
