"""Reproducibly import V2 rows without changing the original Markdown."""
import html
import json
import re
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POSITIONS = {"Verb": "verb", "Adjective/Adverb": "adjective-adverb", "Noun": "noun", "Phrase": "phrase"}
# A small, explicitly curated term map, not a model's predicted classification.
DOMAINS = {
    "voxelwise": ["医学影像"], "abdominal": ["医学", "解剖学"],
    "sagittal view": ["医学影像", "解剖学"], "axial view": ["医学影像", "解剖学"],
    "coronal view": ["医学影像", "解剖学"], "mediastinal structures": ["医学", "解剖学"],
    "knowledge distillation": ["机器学习"], "latent space": ["机器学习"],
    "receptive field": ["计算机视觉"], "group lasso": ["统计学", "机器学习"],
    "harmonic mean": ["数学"], "posteriori probability": ["统计学"],
    "linear superposition": ["数学"], "composite functions": ["数学"],
}


def plain(value):
    return html.unescape(re.sub(r"<[^>]+>", "", value)).strip().strip("*`").strip()


def parse_markdown(text):
    entries = []
    position = None
    for line_number, line in enumerate(text.splitlines(), 1):
        if line.startswith("## "):
            position = POSITIONS.get(line[3:].split(" <")[0].strip())
        if not position or not line.startswith("|"):
            continue
        cells = re.split(r"(?<!\\)\|", line.strip().strip("|"))
        for offset in range(0, len(cells) - 3, 4):
            number, term, meaning, details = [x.strip() for x in cells[offset:offset + 4]]
            if not number.isdigit() or not term or (term == "word" and meaning == "中文"):
                continue
            match = re.search(r"`([^`]+)`", details)
            example = plain(match.group(1)) if match else ""
            source = plain(details.split("`", 2)[-1]) if match else ""
            if example.lower() in {"sentence.", "sentence"}:
                example, source = "", ""
            entries.append({
                "id": str(uuid.uuid5(uuid.NAMESPACE_URL, f"vocab-v2:{line_number}:{offset}")),
                "term": plain(term), "meaning": plain(meaning), "pos": position,
                "domains": DOMAINS.get(plain(term).lower(), []), "tags": [],
                "example": example, "source": source, "source_url": "",
                "owner_id": None, "author_name": "Jing Zhang · 原始词表",
                "provenance": f"glossary_v2.md:L{line_number}", "revision": 1,
            })
    return entries


def main():
    entries = parse_markdown((ROOT / "docs/glossary_v2.md").read_text(encoding="utf-8"))
    target = ROOT / "docs/data/vocabulary.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    payload = json.dumps(entries, ensure_ascii=False)
    sql = "-- Generated by scripts/migrate_glossary.py. Re-runs never overwrite community edits.\n"
    sql += "insert into public.entries (id, term, meaning, pos, domains, tags, example, source, source_url, author_name, provenance)\n"
    sql += "select id, term, meaning, pos, domains, tags, example, source, source_url, author_name, provenance\n"
    sql += "from jsonb_to_recordset($vocab$" + payload + "$vocab$::jsonb) as x(\n"
    sql += "id uuid, term text, meaning text, pos text, domains text[], tags text[], example text, source text, source_url text, author_name text, provenance text)\non conflict (id) do nothing;\n"
    (ROOT / "supabase/seed.sql").write_text(sql, encoding="utf-8")
    print(f"Imported {len(entries)} entries, {sum(bool(e['example']) for e in entries)} with examples.")


if __name__ == "__main__":
    main()
